### ISSUE TITLE
FakeRewardDao insertReward fun is not correct

### ISSUE THREAD

**Issue by ANIKINKIRILL** [FlorianWalther/IncentiveTimer#2]
```
updateRewardMap {
            this[reward.id] = rewardWithId
 }
```
may be u should do this ?

```
updateRewardMap {
            this[rewardWithId.id] = rewardWithId
 }
```

because in ure RewardDao u have REPLACE strategy. so u will be replacing reward and put new one, with new id

**Comment by florianwalther** [comment]
Thank you for pointing this out! I fixed it and will push the changes soon!
